name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
        postgres:
          image: trufflesuite/ganache-cli:latest
          ports:
            - 8545:8545
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5


    steps:
    - name: Set up Go 1.20.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Start ganache-cli deterministically
      run: ganache-cli -d

    - name: Start server
      run: make run

    - name: Test
      run: make test